schema_version = "1.0.0"

id = "t3d_gn_presets_cn"
version = "1.5.1"
name = "T3D GN Presets CN"
tagline = "多功能几何节点实用节点组集合 汉化 By Con幺幺"
maintainer = "Tamil Selvan"
type = "add-on"
website = "https://github.com/CashewTeam/T3D-GN-Presets-CN"
tags = ["Geometry Nodes"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Tamil Selvan"]

[permissions]
files = "For Loading node groups from .blend file"
