schema_version = "1.0.0"

id = "t3d_gn_presets"
version = "1.5.0"
name = "T3D GN Presets"
tagline = "T3D GN Presets is a versatile collection of procedural node groups, enhancing your workflow with Geometry Nodes"
maintainer = "Tamil Selvan"
type = "add-on"
permissions = ["files"]
website = "https://github.com/Tams3d/T3D-GN-Presets"
tags = ["Geometry Nodes"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Tamil Selvan"]
