name: Black Code Formatter

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: |
        python -m pip install --upgrade pip
        pip install black

    - run: black --check --verbose .
