name: Package Repository

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Package Repository
      run: |
        # Create a zip file of the repository excluding .git and Changelogs
        zip -r T3D-GN-Presets.zip . -x ".git/*" "Changelogs/*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: T3D-GN-Presets
        path: T3D-GN-Presets.zip
