name: Zip on Commit

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip Repository
      run: |
        # Exclude "Changelogs" folder and any file/folder starting with ".git"
        zip -r T3D-GN-Presets.zip . -x "Changelogs/*" -x ".git*"

        # Excluded files: Files under "Changelogs" folder and any file/folder starting with ".git"

    - name: Upload Zip
      uses: actions/upload-artifact@v2
      with:
        name: T3D-GN-Presets
        path: T3D-GN-Presets.zip

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job completes before this one
    steps:
    - name: Get Artifact URL
      id: download
      uses: dawidd6/action-download-artifact@v2
      with:
        name: T3D-GN-Presets
        workflow: "Zip on Commit"

    - name: Provide Download Link
      run: echo "Download the zip file [here](\${{ steps.download.outputs.artifact_url }})"
      # This step provides a clickable link to download the zip file
