name: Package Repository

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Package Code
      run: |
        # Create a zip file excluding files starting with ".git" and folders named "Changelogs"
        zip -r T3D-GN-presets.zip . -x ".git/*" -x "Changelogs/*"

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: T3D-GN-presets
        path: T3D-GN-presets.zip
