name: Package Repository

on:
  push:
    branches:
      - Master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Folder and Copy Files
      run: |
        mkdir T3D-GN-presets
        find . -type f -not -path './.git/*' -not -path './Changelog/*' -exec cp --parents {} T3D-GN-presets \;

    - name: Zip Folder
      run: zip -r T3D-GN-presets.zip T3D-GN-presets

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: T3D-GN-presets
        path: T3D-GN-presets.zip
