name: Format and Package Workflow

on:
  push:
    branches:
      - master

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format Code
      run: |
        black .  # Format all Python files in the repository

  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Package Code
      run: |
        # Create a zip file excluding files starting with ".git" and folders named "Changelogs"
        zip -r T3D-GN-presets.zip . -x ".git/*" -x "Changelogs/*"

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: T3D-GN-presets
        path: T3D-GN-presets.zip
